version: "3.8"

services:
  web:
    image: nginx:alpine
    restart: always
    attach: false
    volumes:
      - ./packwiz:/usr/share/nginx/html/packwiz:ro
      - ./minecraft:/usr/share/nginx/html/minecraft:ro
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565" # minecraft
      - "8123:8100" # bluemap
    restart: always
    attach: true
    environment:
      TYPE: "FABRIC"
      PACKWIZ_URL: "http://web/packwiz/pack.toml"
      EULA: true
      MOTD: "CCH Server"
      DIFFICULTY: "HARD"
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 6
      OPS_FILE: "http://web/minecraft/ops.json"
      ENABLE_WHITELIST: false
      MEMORY: "2G"
      USE_AIKAR_FLAGS: true
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
