version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565" # minecraft
      - "19132:19132/tcp" # bedrock
      - "19132:19132/udp" # bedrock
      - "8100:80" # bluemap
    restart: always
    environment:
      TYPE: "FABRIC"
      PACKWIZ_URL: "https://ryleu.me/cch-mc-server/packwiz/pack.toml"
      EULA: true
      MOTD: "CCH Server"
      DIFFICULTY: "HARD"
      SEED: "-7203507603979108244"
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 6
      OPS_FILE: "https://ryleu.me/cch-mc-server/minecraft/ops.json"
      WHITELIST_FILE: "https://ryleu.me/cch-mc-server/minecraft/whitelist.json"
      MEMORY: "6G"
      USE_AIKAR_FLAGS: true
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
