version: "3.8"

services:
  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./packwiz:/usr/share/nginx/html/packwiz:ro
      - ./minecraft:/usr/share/nginx/html/minecraft:ro
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565" # minecraft
      - "8100:8100" # bluemap
    restart: always
    attach: true
    environment:
      TYPE: "FOLIA"
      PACKWIZ_URL: "http://web/packwiz/pack.toml"
      EULA: true
      MOTD: "CCH Server"
      DIFFICULTY: "HARD"
      SEED: "-7203507603979108244"
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 12
      OPS_FILE: "http://web/minecraft/ops.json"
      ENABLE_WHITELIST: false
      MEMORY: "8G"
      USE_AIKAR_FLAGS: true
      VERSION: "1.20.2"
      ENFORCE_SECURE_PROFILE: false
    volumes:
      - ./data:/data
