name = "cch"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c3044a1953e70557e22988d80bc58158ce8b377649dffad748c822c61baa8152"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
