name = "cch"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1a5e26ff56a31e94305193580c26d731ae41fb48bf17f249f376883ad767354"

[versions]
fabric = "0.14.24"
minecraft = "1.20.2"
