name = "cch"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "960d9266354250f04fd1b5400a3fb00cf253da78b1dd764ee05c32afd0ba331c"

[versions]
minecraft = "1.20.2"
